### ISSUE TITLE
Missing test users in demo.sql.gz

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#27]
Previous prime has other usernames to test as documented upon:

https://github.com/unee-t/bugzilla-customisation#login-info-set-by-sqldemosqlgz

Now there only seems to be a **administrator@example.com** account?

<img src="https://s.natalian.org/2017-12-08/1512702210_2558x1406.png">

If you want just one Administrator to begin with, can you perhaps document how to create users?

Idea of the demo.sql.gz in my mind is to be able to quickly search for bugs, login as a user, ensure permissions are correct. Starting from a blank slate with just an administrator account would be inconvenient and time waste from a testing POV!

**Comment by franck-boullier** [comment]
I am currently working on a script to simulate the creation of as many users and as many units as we need so we can do stress tests.
The script is not ready yet (should hopefully be by the end of the day.

In the meantime I suggest that you use the dump for the dev environment for now.
I don't want to publish this as there are sensitive information there.

My suggestion once the dump from the dev has been restored is to reset the password for the administrator user using the BZ ./checksetup.pl script

**Comment by franck-boullier** [comment]
command is
 ./checksetup.pl  --reset-password=user@domain.com

**Comment by kaihendry** [comment]
Not quite sure why you need a script. Before I just created the profiles manually and dumped the db to demo.sql

**Comment by franck-boullier** [comment]
In order to stress test the performances, it is important to be able to create several demo configurations.

The 'seed' database 'demo.sql.gz' is meant to create an environment with the smallest possible footprint.

The demo users are created with a [SQL script](https://github.com/unee-t/bz-database/tree/master/demo-test%20environment) so the developer can decide which number of users and number of units he wants to create in the installation he chooses to deploy
