### ISSUE TITLE
How about some demo cases?

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#61]
```
[hendry@t480s tmp]$  curl -s https://raw.githubusercontent.com/unee-t/bugzilla-customisation/master/sql/demo.sql.gz | zgrep -A5 'Data for the table `bugs`'
/*Data for the table `bugs` */

/*Table structure for table `bugs_activity` */

DROP TABLE IF EXISTS `bugs_activity`;

[hendry@t480s tmp]$
```

**Comment by franck-boullier** [comment]
Agreed
It is on the 'to do' list
I have 2 options 2 do that:
1- I need to get some of the cases from the DEV, sanitize the data and make sure that the dates are correctly reset to be relative to the day the environment is created
2- create a bunch of scenario and have an automated way to run these so that new cases are automatically created when we restore an environment (the Uilicious guys may help with that)

It's going to take me a couple of days to do option 1 and I need to find the time for that 😓 ...

**Comment by kaihendry** [comment]
I think https://documentation.unee-t.com/2018/03/01/introduction-to-the-demo-environment/ is good enough
