### ISSUE TITLE
Unclear process to release in production

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#70]
What is the process to release this in the production environment?

**Comment by kaihendry** [comment]
Production deployments are triggered on tagged releases like the frontend.

This is codified by "tags: true" in https://github.com/unee-t/bugzilla-customisation/blob/master/.travis.yml

**Comment by franck-boullier** [comment]
@kaihendry the mechanism is clear (tagging) but the process is not:
- when do we tag? Do we have any criteria to decide that a release should be done or not?
- who is responsible for tests?

**Comment by kaihendry** [comment]
We tag when we want to make a release to customers. Criteria ultimately should be not to cause a bad UX for the customer. i.e. be aware of any dependencies / migrations and anything that can break things. And to do it as often as possible. Fast production development cycles are especially important at this stage. Solicit feedback from users when a new feature is pushed.

A "release manager", I was assuming it was you, makes that call. In previous roles as a release manager, I review the commits, and conduct my own testing before rubber stamping the release, since I am responsible.

To make life easier, I would employ UIlicious to create tests on flows we care about. But things like adding a form control https://github.com/unee-t/frontend/issues/405 can break things. https://media.dev.unee-t.com/2018-07-24/uilicious.mp4

**Comment by franck-boullier** [comment]
Pending: Document the release process (in the ReadMe?) and make sure people in charge know what they have to.
